import { MovieType } from './types';

export const movies: MovieType[] = [
  {
    id: '1',
    title: 'Inception',
    overview: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    poster_path: '/images/inception.jpg',
    backdrop_path: '/images/inception-backdrop.jpg',
    release_date: '2010-07-16',
    vote_average: 8.8,
    runtime: 148,
    genre_ids: [28, 878, 53],
    posterUrl: '/images/inception.jpg',
    backdropUrl: '/images/inception-backdrop.jpg',
    year: 2010,
    rating: 8.8,
    duration: '2h 28min',
    genres: ['Action', 'Sci-Fi', 'Thriller'],
    cast: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Ellen Page'],
    director: 'Christopher Nolan'
  },
  {
    id: '2',
    title: 'The Dark Knight',
    overview: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    poster_path: '/images/dark-knight.jpg',
    backdrop_path: '/images/dark-knight-backdrop.jpg',
    release_date: '2008-07-18',
    vote_average: 9.0,
    runtime: 152,
    genre_ids: [28, 80, 18],
    posterUrl: '/images/dark-knight.jpg',
    backdropUrl: '/images/dark-knight-backdrop.jpg',
    year: 2008,
    rating: 9.0,
    duration: '2h 32min',
    genres: ['Action', 'Crime', 'Drama'],
    cast: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart'],
    director: 'Christopher Nolan'
  },
  {
    id: '3',
    title: 'Interstellar',
    overview: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
    poster_path: '/images/interstellar.jpg',
    backdrop_path: '/images/interstellar-backdrop.jpg',
    release_date: '2014-11-07',
    vote_average: 8.6,
    runtime: 169,
    genre_ids: [12, 18, 878],
    posterUrl: '/images/interstellar.jpg',
    backdropUrl: '/images/interstellar-backdrop.jpg',
    year: 2014,
    rating: 8.6,
    duration: '2h 49min',
    genres: ['Adventure', 'Drama', 'Sci-Fi'],
    cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'],
    director: 'Christopher Nolan'
  },
  {
    id: '4',
    title: 'Pulp Fiction',
    overview: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
    poster_path: '/images/pulp-fiction.jpg',
    backdrop_path: '/images/pulp-fiction-backdrop.jpg',
    release_date: '1994-10-14',
    vote_average: 8.9,
    runtime: 154,
    genre_ids: [80, 18],
    posterUrl: '/images/pulp-fiction.jpg',
    backdropUrl: '/images/pulp-fiction-backdrop.jpg',
    year: 1994,
    rating: 8.9,
    duration: '2h 34min',
    genres: ['Crime', 'Drama'],
    cast: ['John Travolta', 'Samuel L. Jackson', 'Uma Thurman'],
    director: 'Quentin Tarantino'
  },
  {
    id: '5',
    title: 'The Matrix',
    overview: 'A computer programmer discovers that reality as he knows it is a simulation created by machines, and joins a rebellion to break free.',
    poster_path: '/images/matrix.jpg',
    backdrop_path: '/images/matrix-backdrop.jpg',
    release_date: '1999-03-31',
    vote_average: 8.7,
    runtime: 136,
    genre_ids: [28, 878],
    posterUrl: '/images/matrix.jpg',
    backdropUrl: '/images/matrix-backdrop.jpg',
    year: 1999,
    rating: 8.7,
    duration: '2h 16min',
    genres: ['Action', 'Sci-Fi'],
    cast: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss'],
    director: 'Lana Wachowski'
  }
];